### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BLMeltdown** [jamesboehmer/verium-docker#1]
Hello
I am pleased to see this project as it seems interesting, but I would like to ask what is the difference with the current vault, which allows for solo mining already? 
Is it higher performance?

**Comment by jamesboehmer** [comment]
It's so that you don't have to run the miner on your personal computer.  I built this image to run on a pico cluster under my desk.

**Comment by BLMeltdown** [comment]
Oh, ok, thanks. That make sense. On such cluster do you have good mining results/hashrate?

**Comment by jamesboehmer** [comment]
TBH, I haven't run it in a while.  I forget the actual rates, but they were about comparable to my macbook pro.

**Comment by BLMeltdown** [comment]
Ok thanks;)
